# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Alvis-Saa
version:      0.2
version_from: lib/Alvis/Saa.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    Fcntl:                         0
    IO::Select:                    0
    IO::Socket:                    0
    Sys::Hostname:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
